"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const Tree_1 = require("./Tree");
const forest = [];
forest.push(new Tree_1.Tree(1, 1, "Oak", "Green", "Rough"));
forest.push(new Tree_1.Tree(2, 3, "Pine", "Dark Green", "Smooth"));
forest.push(new Tree_1.Tree(5, 1, "Oak", "Green", "Rough"));
forest.push(new Tree_1.Tree(10, 6, "Cherry", "Pink", "Glossy"));
forest.push(new Tree_1.Tree(15, 3, "Oak", "Green", "Rough"));
console.log("\n--- Forest Display ---");
forest.forEach(tree => tree.display());
