"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const AudioSystem_1 = require("./AudioSystem");
const Projector_1 = require("./Projector");
const Screen_1 = require("./Screen");
const MoviePlayer_1 = require("./MoviePlayer");
const audio = new AudioSystem_1.AudioSystem();
const projector = new Projector_1.Projector();
const screen = new Screen_1.Screen();
const player = new MoviePlayer_1.MoviePlayer();
console.log("\n=== Starting Movie Experience ===");
screen.lower();
projector.turnOn();
projector.setMode("Cinema");
audio.turnOn();
audio.setVolume(7);
player.play("Inception");
console.log("\n=== Ending Movie Experience ===");
player.stop();
screen.raise();
